name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save actions-example-k8s-1-16

    - name: Deploy new code
      run: kubectl rollout restart ${{ secrets.DEPLOYMENT_NAME }}
